<?php 
echo $this->partial('partials/navbar.phtml',
		array('selected' => $this->navdata));
?>

<div class="container-fluid-full">

		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				
				<div class="row-fluid actions">
													
					<input type="text" class="search span12" placeholder="..." />
				
				</div>	
				
				<?php 
					echo $this->partial('partials/mainmenu.phtml',
							array('data' => $this->data));
					?>
				
				
			</div>
			<!-- end: Main Menu -->
						
				<!-- start: Content -->
				<div id="content" class="span10">
				
						
						<div class="row-fluid">		
						<div class="box span12">
							<div class="box-header" data-original-title="">
								<h2><i class="icon-user"></i><span class="break"></span>Agents List</h2>
								<div class="box-icon">
									<a href="#" class="btn-setting"><i class="icon-wrench"></i></a>
									<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
									<a href="#" class="btn-close"><i class="icon-remove"></i></a>
								</div>
							</div>
							<div class="box-content">
								<table class="table table-striped table-bordered bootstrap-datatable datatable">
								  <thead>
									  <tr>
										  <th>Name</th>
										  <th>Branch</th>
										  <th>Contact Number</th>
										  
										  <th>Address</th>
										  <th>Applicants Submitted</th>
										  <th>Applicants Deployed</th>
										  <th>Status</th>
											
									  </tr>
								  </thead>   
								  <tbody>
								  
								  <?php 
								  	$agentsdata = $this->agents;
								  	$branch = $this->branch;
								  	$branch_mapper = new Application_Model_BranchMapper();
								  	
								  	foreach($agentsdata as $agent){

										$brancharrayRes = $branch_mapper->getBranchById($agent['BRANCH_ID']);
										$arrayRes = $brancharrayRes->__getProperties();
								  		echo '<tr>
												<td>'.$agent['AGENTS_NAME'].'</td>
												<td class="center">'.$arrayRes['BRANCH_NAME'].'</td>
												<td class="center">'.$agent['AGENTS_CONTACTNUMBER'].'</td>
												
												<td class="center">
													'.$agent['AGENTS_ADDRESS'].'
												</td>
												<td class="center"> - count -</td>
												<td class="center"> - count -</td>
												<td class="center">
													<span class="label label-success">Active</span>
												</td>
											</tr>';
								  	}
								  ?>
								  
								  
									
								  </tbody>
							  </table>            
							</div>
						</div><!--/span-->
						
						<div class="row-fluid">
							<div class="box span12">
								<div class="box-header">
									<h2><i class="icon-edit"></i>Create New Agent Data</h2>
									<div class="box-icon">
										<a href="#" class="btn-setting"><i class="icon-wrench"></i></a>
										<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
										<a href="#" class="btn-close"><i class="icon-remove"></i></a>
									</div>
								</div>
								<div class="box-content">
									<form class="form-horizontal" action="/Agentbranch/newagent" method="post" />
									  <fieldset>
										<div class="control-group ">
											<label for="inputSuccess" class="control-label">Branch Location</label>
											<div class="controls">
											  <select id="selectError3" name="inputAgentsBranchID">
											  		<option value=""> - Select Branch - </option>
											  		<?php 
											  		
											  		$allbranch = $this->allbranch;
											  		foreach($allbranch as $branch) {
											  			echo '<option value="'.$branch['BRANCH_ID'].'">'.$branch['BRANCH_CODENUMBER'].' - '.$branch['BRANCH_NAME'].'</option>';	
											  		}
											  		?>
											  </select>
											</div>
											
											
											
										  </div>
										  <div class="control-group ">
											<label for="inputSuccess" class="control-label">Agent Name</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputAgentsName" >
											</div>
										  </div>
										  <div class="control-group ">
											<label for="inputSuccess" class="control-label">Agent Contact Numbers</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputAgentsContactNumbers" >
											</div>
										  </div>
										  <div class="control-group ">
											<label for="inputSuccess" class="control-label">Agent Address</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputAgentsAddress" >
											</div>
										  </div>
										  <div class="control-group ">
											<label for="inputSuccess" class="control-label">Agent Remarks</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputAgentsRemarks" />
											</div>
										  </div>
										  <div class="control-group ">
											<div class="controls">
											  <button class="btn btn-primary" type="submit" id="inputAgentsDataSubmit" name="inputAgentsDataSubmit">Submit</button>
											</div>
										  </div>
									  </fieldset>
									</form>   
			
								</div>
							</div><!--/span-->
			
						</div><!--/row-->
											
						<div class="row-fluid">
							<div class="box span12">
								<div class="box-header">
									<h2><i class="icon-edit"></i>Create New Branch Data </h2>
									<div class="box-icon">
										<a href="#" class="btn-setting"><i class="icon-wrench"></i></a>
										<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
										<a href="#" class="btn-close"><i class="icon-remove"></i></a>
									</div>
								</div>
								<div class="box-content">
									<form name="newbranch" class="form-horizontal" action="/Agentbranch/newbranch" method="post">
									  <fieldset>
										<div class="control-group ">
											<label for="inputSuccess" class="control-label">Code Number</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputBranchDataCodeNumber" />
											</div>
										  </div>
										  <div class="control-group ">
											<label for="inputSuccess" class="control-label">Name</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputBranchDataName" />
											</div>
										  </div>
										  <div class="control-group ">
											<label for="inputSuccess" class="control-label">Address</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputBrachDataAddress" />
											</div>
										  </div>
										  <div class="control-group ">
											<label for="inputSuccess" class="control-label">Remarks</label>
											<div class="controls">
											  <input type="text" id="inputSuccess" name="inputBranchDataRemarks" />
											</div>
										  </div>
										  <div class="control-group ">
											<div class="controls">
											  <button class="btn btn-primary" type="submit" id="inputBranchDataSubmit" name="inputBranchDataSubmit">Submit</button>
											</div>
										  </div>
									  </fieldset>
									</form>   
			
								</div>
							</div><!--/span-->
			
						</div><!--/row-->

				
				</div>
				<!-- end: Content -->
					
			</div><!--/fluid-row-->
			
		
		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>
		
		<div class="clearfix"></div>
		
		<?php 
					echo $this->partial('partials/footer.phtml',
							array('data' => $this->data));
					?>
</div>




