<?php 
echo $this->partial('partials/navbar.phtml',
		array('selected' => $this->navdata));


$sysuserSess = new Zend_Session_Namespace('SYSUSER_SESS');

?>

<div class="container-fluid-full">

		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				
				<div class="row-fluid actions">
													
					<input type="text" class="search span12" placeholder="..." />
				
				</div>	
				
				<?php 
					echo $this->partial('partials/mainmenu.phtml',
							array('data' => $this->data));
					?>
				
				
			</div>
			<!-- end: Main Menu -->
						
			<!-- start: Content -->
			<div id="content" class="span10">
			
						
			<div class="row-fluid">
				
				<div class="span3 smallstat box mobileHalf" ontablet="span6" ondesktop="span3">
					<div class="boxchart-overlay blue">
						<div class="boxchart">5,6,7,2,0,4,2,4,8,2,3,3,2</div>
					</div>	
					<span class="title">Applicants</span>
					<span class="value">4 589</span>
				</div>
				
				<div class="span3 smallstat box mobileHalf" ontablet="span6" ondesktop="span3">
					<div class="boxchart-overlay red">
						<div class="boxchart">1,2,6,4,0,8,2,4,5,3,1,7,5</div>
					</div>	
					<span class="title">Deployed</span>
					<span class="value">789</span>
				</div>
				
				<?php 
				
				if($sysuserSess->sysuser['SYS_USERS_GROUP_ID'] == 1 || $sysuserSess->sysuser['SYS_USERS_GROUP_ID'] == 3) {
				
				?>
					<div class="span3 smallstat box mobileHalf noMargin" ontablet="span6" ondesktop="span3">
						<i class="icon-upload-alt green"></i>
						<span class="title">Expense</span>
						<span class="value">P1 999,99</span>
					</div>
					
					<div class="span3 smallstat mobileHalf box" ontablet="span6" ondesktop="span3">
						<i class="icon-money yellow"></i>
						<span class="title">Account</span>
						<span class="value">P19 999,99</span>
					</div>
				<?php 
				}
				?>
			
			</div>	
				
				
				<?php 
					echo $this->partial('partials/applicantdatamenu.phtml',
							array('data' => $this->data));
					?>
			
					
			</div>
			<!-- end: Content -->
				
		</div><!--/fluid-row-->
		

		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>
		
		<div class="clearfix"></div>
		
		<?php 
					echo $this->partial('partials/footer.phtml',
							array('data' => $this->data));
					?>
</div>