<?php 
echo $this->partial('partials/navbar.phtml',
		array('selected' => $this->navdata));
?>

<div class="container-fluid-full">

		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				
				<div class="row-fluid actions">
													
					<input type="text" class="search span12" placeholder="..." />
				
				</div>	
				
				<?php 
					echo $this->partial('partials/mainmenu.phtml',
							array('data' => $this->data));
					?>
				
				
			</div>
			<!-- end: Main Menu -->
						
				<!-- start: Content -->
				<div id="content" class="span10">
				
						
						<div class="row-fluid">
							<div class="box span12">
								<div class="box-content alerts">
									<?php 
										$response = $this->response;
										if($response['newsaveheadofficeexp']) {
											echo '
												<div class="alert alert-success">
										<button type="button" class="close" data-dismiss="alert">×</button>
										<strong>Well done!</strong> Head Office Expenses Successfully saved.. 
									</div>
		
												';
										}
									?>
									
									
								</div>
					
								<div class="box-header">
									<h2><i class="icon-edit"></i>COMMISSION EXPENSES</h2>
									<div class="box-icon">
										<a href="#" class="btn-setting"><i class="icon-wrench"></i></a>
										<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
										<a href="#" class="btn-close"><i class="icon-remove"></i></a>
									</div>
								</div>
								<div class="box-content">
										<form class="form-horizontal" action="/Accounting/setaccountingexpensesutilities" method="post" />
											  <fieldset>
											  		<input type="hidden" name="newaccountingexpensesutilities" id="newaccountingexpensesutilities" value="1">
												  <div class="control-group ">
												  	<?php 
												  	date_default_timezone_set("Asia/Manila");
												  	$current = date("m/d/Y");
												  	?>
													<label for="todaysDate" class="control-label">Date : </label>
													<div class="controls">
													  <input type="text" id="todaysDate" name="todaysDate" value="<?php echo $current;?>" readonly/>
													</div>
												  </div>
													
												  <div class="control-group" id="DIV_ACCOUNTINGEXPENSES_COMMISSION_BRANCHNO">
													<label for=ACCOUNTINGEXPENSES_COMMISSION_BRANCHNO class="control-label">Branch No.</label>
													<div class="controls">
													  <input type="text" id="ACCOUNTINGEXPENSES_COMMISSION_BRANCHNO" name="ACCOUNTINGEXPENSES_COMMISSION_BRANCHNO" >
													</div>
												  </div>
												  
												  <div class="control-group" id="DIV_ACCOUNTINGEXPENSES_COMMISSION_AGENTNAME">
													<label for=ACCOUNTINGEXPENSES_COMMISSION_BRANCHNO class="control-label">Agent Name </label>
													<div class="controls">
													  <input type="text" id="ACCOUNTINGEXPENSES_COMMISSION_AGENTNAME" name="ACCOUNTINGEXPENSES_COMMISSION_AGENTNAME" >
													</div>
												  </div>
												  
												  <div class="control-group" id="DIV_ACCOUNTINGEXPENSES_COMMISSION_APPLICANTNAME">
													<label for=ACCOUNTINGEXPENSES_COMMISSION_BRANCHNO class="control-label">Branch No.</label>
													<div class="controls">
													  <input type="text" id="ACCOUNTINGEXPENSES_COMMISSION_APPLICANTNAME" name="ACCOUNTINGEXPENSES_COMMISSION_APPLICANTNAME" >
													</div>
												  </div>
												  
												   <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_COMMISSION_AMOUNTEXP" class="control-label">Amount Exp</label>
														<div class="controls">
														  <div class="input-prepend">	
														  	<span class="add-on">&#8369 </span> <input type="text" id="ACCOUNTINGEXPENSES_COMMISSION_AMOUNTEXP" value="0" name="ACCOUNTINGEXPENSES_COMMISSION_AMOUNTEXP" >
															</div>
														</div>
												  </div>
												  
												  
												  
												  <div class="control-group" id="DIV_ACCOUNTINGEXPENSES_COMMISSION_OTHERSNOTE">
													<label for=ACCOUNTINGEXPENSES_COMMISSION_OTHERSNOTE class="control-label">Others Exp Note*</label>
													<div class="controls">
													  <input type="text" id="ACCOUNTINGEXPENSES_COMMISSION_OTHERSNOTE" name="ACCOUNTINGEXPENSES_COMMISSION_OTHERSNOTE" >
													</div>
												  </div>
												 
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_COMMISSION_OTHERSEXP" class="control-label">Others Exp Amount</label>
														<div class="controls">
														  <div class="input-prepend">	
														  	<span class="add-on">&#8369 </span> <input type="text" id="ACCOUNTINGEXPENSES_COMMISSION_OTHERSEXP" value="0" name="ACCOUNTINGEXPENSES_COMMISSION_OTHERSEXP" >
															</div>
														</div>
												  </div>
												  
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_COMMISSION_TOTALEXP" class="control-label">Total Expenses</label>
														
														<div class="controls">
															<div class="input-prepend">
														 <span class="add-on">&#8369</span> <input type="text" id="ACCOUNTINGEXPENSES_COMMISSION_TOTALEXP" name="ACCOUNTINGEXPENSES_COMMISSION_TOTALEXP" readonly>
															</div>
														</div>
														
												  </div>
												  
												  <div class="control-group">
													  <label class="control-label" for="ACCOUNTINGEXPENSES_UTILITIES_DATERELEASE">Date Release Payment</label>
													  <div class="controls">
														<input type="text" class="input-xlarge datepicker" id="ACCOUNTINGEXPENSES_UTILITIES_DATERELEASE" name="ACCOUNTINGEXPENSES_UTILITIES_DATERELEASE" value="" />
													  </div>
													</div>
													 
												  <div class="control-group ">
													<div class="controls">
													  <button class="btn btn-primary" type="submit" id="inputAccntCommissionSubmit" name="inputAccntCommissionSubmit">Save and Continue</button>
													</div>
												  </div>
												  
											  </fieldset>
										</form>
									</div>	
								</div>	   
						</div><!--/row-->	

				
				</div>
				<!-- end: Content -->
					
			</div><!--/fluid-row-->
			
		
		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>
		
		<div class="clearfix"></div>
		
		<?php 
					echo $this->partial('partials/footer.phtml',
							array('data' => $this->data));
					?>
</div>




