<?php 
echo $this->partial('partials/navbar.phtml',
		array('selected' => $this->navdata));
?>

<div class="container-fluid-full">

		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				
				<div class="row-fluid actions">
													
					<input type="text" class="search span12" placeholder="..." />
				
				</div>	
				
				<?php 
					echo $this->partial('partials/mainmenu.phtml',
							array('data' => $this->data));
					?>
				
				
			</div>
			<!-- end: Main Menu -->
						
				<!-- start: Content -->
				<div id="content" class="span10">
				
						
						<div class="row-fluid">
							<div class="box span12">
								<div class="box-content alerts">
									<?php 
										$response = $this->response;
										if($response['newsaveheadofficeexp']) {
											echo '
												<div class="alert alert-success">
										<button type="button" class="close" data-dismiss="alert">×</button>
										<strong>Well done!</strong> Head Office Expenses Successfully saved.. 
									</div>
		
												';
										}
									?>
									
									
								</div>
					
								<div class="box-header">
									<h2><i class="icon-edit"></i>HEAD OFFICE EXPENSES</h2>
									<div class="box-icon">
										<a href="#" class="btn-setting"><i class="icon-wrench"></i></a>
										<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
										<a href="#" class="btn-close"><i class="icon-remove"></i></a>
									</div>
								</div>
								<div class="box-content">
										<form class="form-horizontal" action="/Accounting/setaccountingexpensesheadoffice" method="post" />
											  <fieldset>
											  		<input type="hidden" name="newaccountingexpensesheadoffice" id="newaccountingexpensesheadoffice" value="1">
												  <div class="control-group ">
												  	<?php 
												  	date_default_timezone_set("Asia/Manila");
												  	$current = date("m/d/Y");
												  	?>
													<label for="todaysDate" class="control-label">Date : </label>
													<div class="controls">
													  <input type="text" id="todaysDate" name="todaysDate" value="<?php echo $current;?>" readonly/>
													</div>
												  </div>
												  
												  <div class="control-group ">
													<label for="ACCOUNTINGEXPENSES_HEADOFFICE_BNAME" class="control-label">Branch No.</label>
													<div class="controls">
													  <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_BNAME" name="ACCOUNTINGEXPENSES_HEADOFFICE_BNAME" >
													</div>
												  </div>
												  <div class="control-group ">
													<label for="ACCOUNTINGEXPENSES_HEADOFFICE_PAYMENTFORM" class="control-label">Payment For</label>
													<div class="controls">
													  <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_PAYMENTFORM" name="ACCOUNTINGEXPENSES_HEADOFFICE_PAYMENTFORM" >
													</div>
												  </div>
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_APPLICANTNAME" class="control-label">Applicants Name</label>
														<div class="controls">
														  <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_APPLICANTNAME" name="ACCOUNTINGEXPENSES_HEADOFFICE_APPLICANTNAME" >
														</div>
												  </div>
												  <div class="control-group">
													  <label class="control-label" for="ACCOUNTINGEXPENSES_HEADOFFICE_ARRIVALDATE">Arrival Date</label>
													  <div class="controls">
														<input type="text" class="input-xlarge datepicker" id="ACCOUNTINGEXPENSES_HEADOFFICE_ARRIVALDATE" name="ACCOUNTINGEXPENSES_HEADOFFICE_ARRIVALDATE" value="" />
													  </div>
													</div>
													
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_ARRIVALFROM_ADDRESS" class="control-label">Arrival From Province</label>
														<div class="controls">
														  <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_ARRIVALFROM_ADDRESS" name="ACCOUNTINGEXPENSES_HEADOFFICE_ARRIVALFROM_ADDRESS" >
														</div>
												  </div>
												  
												  <div class="control-group ">
													<label for="ACCOUNTINGEXPENSES_HEADOFFICE_TRAVELMODE" class="control-label">Travel Mode</label>
													<div class="controls">
													  <select id="ACCOUNTINGEXPENSES_HEADOFFICE_TRAVELMODE" name="ACCOUNTINGEXPENSES_HEADOFFICE_TRAVELMODE">
													  		<option value=""></option>
													  		<option value="Sea">Sea</option>
													  		<option value="Airline">Airline</option>
													  		<option value="Land">Land</option>
													  </select>
													</div>
												  </div>
												  
												 <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_PASSPORT" class="control-label">Passport</label>
														<div class="controls">
														  <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_PASSPORT" name="ACCOUNTINGEXPENSES_HEADOFFICE_PASSPORT" >
														</div>
												  </div>
												  
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_MEDICALEXP" class="control-label">Medical </label>
														<div class="controls">
														  <div class="input-prepend">	
														  	<span class="add-on">&#8369 </span> <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_MEDICALEXP" value="0" name="ACCOUNTINGEXPENSES_HEADOFFICE_MEDICALEXP" >
															</div>
														</div>
												  </div>
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_TESDAEXP" class="control-label">TESDA</label>
														
														<div class="controls">
															<div class="input-prepend">
														 <span class="add-on">&#8369</span> <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_TESDAEXP" value="0" name="ACCOUNTINGEXPENSES_HEADOFFICE_TESDAEXP" >
															</div>
														</div>
														
												  </div>
												  
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_TRAININGEXP" class="control-label">Training</label>
														
														<div class="controls">
															<div class="input-prepend">
														 <span class="add-on">&#8369</span> <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_TRAININGEXP" value="0" name="ACCOUNTINGEXPENSES_HEADOFFICE_TRAININGEXP" >
															</div>
														</div>
												  </div>
												  
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_VISAEXP" class="control-label">Visa</label>
														
														<div class="controls">
															<div class="input-prepend">
														 <span class="add-on">&#8369</span> <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_VISAEXP" value="0" name="ACCOUNTINGEXPENSES_HEADOFFICE_VISAEXP" >
															</div>
														</div>
												  </div>
												  
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_TICKETEXP" class="control-label">Ticket</label>
														
														<div class="controls">
															<div class="input-prepend">
														 <span class="add-on">&#8369</span> <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_TICKETEXP" value="0" name="ACCOUNTINGEXPENSES_HEADOFFICE_TICKETEXP" >
															</div>
														</div>
												  </div>
												  

												  
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_OTHERSEXP" class="control-label">Other Expenses</label>
														
														<div class="controls">
															<div class="input-prepend">
														 <span class="add-on">&#8369</span> <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_OTHERSEXP" value="0" name="ACCOUNTINGEXPENSES_HEADOFFICE_OTHERSEXP" >
															</div>
														</div>
												  </div>
												  
												  <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_OTHERSNOTE" class="control-label">Other Expenses Note</label>
														<div class="controls">
														  <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_OTHERSNOTE" name="ACCOUNTINGEXPENSES_HEADOFFICE_OTHERSNOTE" >
														</div>
												  </div>
												  
												   <div class="control-group ">
														<label for="ACCOUNTINGEXPENSES_HEADOFFICE_TOTALEXP" class="control-label">Total Expenses</label>
														
														<div class="controls">
															<div class="input-prepend">
														 <span class="add-on">&#8369</span> <input type="text" id="ACCOUNTINGEXPENSES_HEADOFFICE_TOTALEXP" name="ACCOUNTINGEXPENSES_HEADOFFICE_TOTALEXP" readonly>
															</div>
														</div>
														
												  </div>
												  
												  <div class="control-group">
													  <label class="control-label" for="ACCOUNTINGEXPENSES_HEADOFFICE_DATEDEPARTURE">Date Departure</label>
													  <div class="controls">
														<input type="text" class="input-xlarge datepicker" id="ACCOUNTINGEXPENSES_HEADOFFICE_DATEDEPARTURE" name="ACCOUNTINGEXPENSES_HEADOFFICE_DATEDEPARTURE" value="" />
													  </div>
													</div>
													 
												  <div class="control-group ">
													<div class="controls">
													  <button class="btn btn-primary" type="submit" id="inputAgentsDataSubmit" name="inputAgentsDataSubmit">Save and Continue</button>
													</div>
												  </div>
											  </fieldset>
										</form>
									</div>	
								</div>	   
						</div><!--/row-->	

				
				</div>
				<!-- end: Content -->
					
			</div><!--/fluid-row-->
			
		
		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>
		
		<div class="clearfix"></div>
		
		<?php 
					echo $this->partial('partials/footer.phtml',
							array('data' => $this->data));
					?>
</div>




