<?php 
echo $this->partial('partials/navbar.phtml',
		array('selected' => $this->navdata));
?>

<div class="container-fluid-full">

		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				
				<div class="row-fluid actions">
													
					<input type="text" class="search span12" placeholder="..." />
				
				</div>	
				
				<?php 
					echo $this->partial('partials/mainmenu.phtml',
							array('data' => $this->data));
					?>
				
				
			</div>
			<!-- end: Main Menu -->
						
			<!-- start: Content -->
			<div id="content" class="span10">
			
					<?php 
					echo $this->partial('partials/applicantdatamenu.phtml',
							array('data' => $this->data));


						$newbiodatasession = new Zend_Session_Namespace('NEW_BIODATA_SESS');
						$newappdata = $newbiodatasession->newappdata;
						
						//Zend_Debug::dump($newappdata);
					?>

						<div class="row-fluid">
							<div class="box span12">
							
								<div class="box-header">
									<h2><i class="icon-edit"></i>FAMILY DATA FOR <b><?php echo $newappdata['APPLICANTS_PERSONAL_DATA_FIRSTNAME'].' '.$newappdata['APPLICANTS_PERSONAL_DATA_LASTNAME']; ?></b></h2>
									<div class="box-icon">
										<a href="#" class="btn-setting"><i class="icon-wrench"></i></a>
										<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
										<a href="#" class="btn-close"><i class="icon-remove"></i></a>
									</div>
								</div>
								<div class="box-content">
										<form class="form-horizontal" action="/applicantdata/newworkexperience" method="post" />
											  <fieldset>
											  	<input type="hidden" id="APPLICANTS_PERSONAL_DATA_ID" name="APPLICANTS_PERSONAL_DATA_ID" value="<?php echo $newappdata['APPLICANTS_PERSONAL_DATA_ID'];?>">
											  	<?php 
												  	$status_mapper = new Application_Model_ApplicantsMaritalstatusSelectorMapper();
												  	$stat = $status_mapper->fetchAllApplicantsMaritalStatusSelector();
												  	//print_r($res);
												  ?>
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Marital Status</label>
													<div class="controls">
													  <select id="selectError3" name="APPLICANTS_FAMILY_DATA_MARITALSTATUS">
													  		<option value=""></option>
													  		<?php 
													  		foreach($stat as $k) {
													  			echo '<option value="'.$k['APPLICANTS_PERSONAL_MARITALSTATUS_ID'].'">'.$k['APPLICANTS_PERSONAL_MARITALSTATUS_VALUE'].'</option>';	
													  		}
													  		?>
													  </select>
													</div>
												  </div>
												<div class="control-group ">
													<label for="inputSuccess" class="control-label">No. of children</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_NOOFCHILDREN" name="APPLICANTS_FAMILY_DATA_NOOFCHILDREN" >
													</div>
												  </div>
												  <!-- 
												  <div class="control-group ">
														<label for="inputSuccess" class="control-label">Ages</label>
														<div class="controls">
														  <input type="text" id="APPLICANTS_FAMILY_DATA_CHILDRENAGES" name="APPLICANTS_FAMILY_DATA_CHILDRENAGES" >
														</div>
												  </div>
												   -->
												  <div class="box-content alerts">
														<div class="alert alert-success">
															<button data-dismiss="alert" class="close" type="button">×</button>
															<strong>Spouse</strong> 
														</div>
													</div>
													
												  <div class="control-group clearfix">
														<label for="inputSuccess" class="control-label">Name of Spouse</label>
														<div class="controls">
														  <input type="text" id="APPLICANTS_FAMILY_DATA_SPOUSEFULLNAME" name="APPLICANTS_FAMILY_DATA_SPOUSEFULLNAME" >
														</div>
												  </div>
												  <div class="control-group clearfix">
														<label for="inputSuccess" class="control-label">Spouse Tel No.</label>
														<div class="controls">
														  <input type="text" id="APPLICANTS_FAMILY_DATA_SPOUSETELNO" name="APPLICANTS_FAMILY_DATA_SPOUSETELNO" >
														</div>
												  </div>
												  <div class="control-group clearfix">
														<label for="inputSuccess" class="control-label">Spouse Occupation</label>
														<div class="controls">
														  <input type="text" id="APPLICANTS_FAMILY_DATA_SPOUSEOCCUPATION" name="APPLICANTS_FAMILY_DATA_SPOUSEOCCUPATION" >
														</div>
												  </div>
												  
												  <div class="box-content alerts">
														<div class="alert alert-success">
															<button data-dismiss="alert" class="close" type="button">×</button>
															<strong>Parents and Siblings</strong> 
														</div>
													</div>
													
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Father's Name</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_FATHERSFULLNAME" name="APPLICANTS_FAMILY_DATA_FATHERSFULLNAME" >
													</div>
												  </div>
												   <div class="control-group ">
													<label for="inputSuccess" class="control-label">Father's Tel No.</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_FATHERSTELNO" name="APPLICANTS_FAMILY_DATA_FATHERSTELNO" >
													</div>
												  </div>
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Father's Occupation</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_FATHERSOCCUPATION" name="APPLICANTS_FAMILY_DATA_FATHERSOCCUPATION" >
													</div>
												  </div>
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Mother's name</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_MOTHERSFULLNAME" name="APPLICANTS_FAMILY_DATA_MOTHERSFULLNAME" />
													</div>
												  </div>
												  
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Mother's Tel No.</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_MOTHERSTELNO" name="APPLICANTS_FAMILY_DATA_MOTHERSTELNO" />
													</div>
												  </div>
												  
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Mother's Occupation</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_MOTHERSOCCUPATION" name="APPLICANTS_FAMILY_DATA_MOTHERSOCCUPATION" />
													</div>
												  </div>
												  
												  <!-- 
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Brothers</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_HOWMANYBROTHER" name="APPLICANTS_FAMILY_DATA_HOWMANYBROTHER" />
													</div>
												  </div>
												  <div class="control-group ">
													<label for="inputSuccess" class="control-label">Sisters</label>
													<div class="controls">
													  <input type="text" id="APPLICANTS_FAMILY_DATA_HOWMANYSISTERS" name="APPLICANTS_FAMILY_DATA_HOWMANYSISTERS" />
													</div>
												  </div>
												   -->
												   
												  <div class="control-group ">
													<div class="controls">
													  <button class="btn btn-primary" type="submit" id="inputFamilydatasubmit" name="inputFamilydatasubmit">Save and Continue</button>
													</div>
												  </div>
											  </fieldset>
										</form>
									</div>	
								</div>	   
						</div><!--/row-->	
			</div>
			<!-- end: Content -->
				
		</div><!--/fluid-row-->
		

		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>
		
		<div class="clearfix"></div>
		
		<?php 
					echo $this->partial('partials/footer.phtml',
							array('data' => $this->data));
					?>
</div>