<?php 
	$data = $this->appdata;
	
	/**
	 *array(68) {
  ["APPLICANTS_PERSONAL_DATA_ID"] => string(1) "1"
  ["APPLICANTS_PERSONAL_DATA_DESIRED_POSITION"] => string(6) "Helper"
  ["APPLICANTS_PERSONAL_DATA_RELIGION"] => string(8) "Christan"
  ["APPLICANTS_PERSONAL_DATA_AGE"] => string(2) "34"
  ["APPLICANTS_PERSONAL_DATA_OTHERSKILLS"] => string(9) "Labandera"
  ["APPLICANTS_PERSONAL_DATA_EXABROAD"] => string(1) "1"
  ["APPLICANTS_PERSONAL_DATA_EXABROAD_YEARS"] => string(2) "na"
  ["APPLICANTS_PERSONAL_DATA_COUNTRY_ABROAD"] => string(2) "NA"
  ["APPLICANTS_PERSONAL_DATA_FIRSTNAME"] => string(5) "Vilma"
  ["APPLICANTS_PERSONAL_DATA_MIDDLENAME"] => string(0) ""
  ["APPLICANTS_PERSONAL_DATA_LASTNAME"] => string(6) "Santos"
  ["APPLICANTS_PERSONAL_DATA_HEIGHT"] => string(3) "5'2"
  ["APPLICANTS_PERSONAL_DATA_WEIGHT"] => string(3) "120"
  ["APPLICANTS_PERSONAL_DATA_GENDER"] => string(1) "2"
  ["APPLICANTS_PERSONAL_DATA_ADDRESS"] => string(9) "Cebu City"
  ["APPLICANTS_PERSONAL_DATA_TELEPHONE"] => string(9) "474657465"
  ["APPLICANTS_PERSONAL_DATA_CELLPHONE"] => string(8) "45674567"
  ["APPLICANTS_PERSONAL_DATA_DATEOFBIRTH"] => string(8) "9/4/1981"
  ["APPLICANTS_PERSONAL_DATA_PLACEOFBIRTH"] => string(9) "Cebu city"
  ["APPLICANTS_PERSONAL_DATA_DATECREATED"] => string(19) "2013-12-21 00:13:34"
  ["APPLICANTS_FAMILY_DATA_MARITALSTATUS"] => NULL
  ["APPLICANTS_FAMILY_DATA_NOOFCHILDREN"] => NULL
  ["APPLICANTS_FAMILY_DATA_CHILDRENAGES"] => NULL
  ["APPLICANTS_FAMILY_DATA_SPOUSEFULLNAME"] => NULL
  ["APPLICANTS_FAMILY_DATA_FATHERSFULLNAME"] => NULL
  ["APPLICANTS_FAMILY_DATA_MOTHERSFULLNAME"] => NULL
  ["APPLICANTS_FAMILY_DATA_SPOUSETELNO"] => NULL
  ["APPLICANTS_FAMILY_DATA_FATHERSTELNO"] => NULL
  ["APPLICANTS_FAMILY_DATA_MOTHERSTELNO"] => NULL
  ["APPLICANTS_FAMILY_DATA_SPOUSEOCCUPATION"] => NULL
  ["APPLICANTS_FAMILY_DATA_FATHERSOCCUPATION"] => NULL
  ["APPLICANTS_FAMILY_DATA_MOTHERSOCCUPATION"] => NULL
  ["APPLICANTS_FAMILY_DATA_HOWMANYBROTHER"] => NULL
  ["APPLICANTS_FAMILY_DATA_HOWMANYSISTERS"] => NULL
  ["APPLICANTS_DAILYSTATUS_CODE"] => string(4) "xx23"
  ["AGENTBRANCH_ID"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_WBPHOTO"] => string(12) "DSC_4050.jpg"
  ["APPLICANTS_DAILYSTATUS_CONTACTNUMBER"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_PASSPORT"] => string(10) "2345234523"
  ["APPLICANTS_DAILYSTATUS_PASSPORTDATEISSUE"] => string(10) "10/06/2011"
  ["APPLICANTS_DAILYSTATUS_PASSPORTDATEEXPIRE"] => string(10) "12/19/2013"
  ["APPLICANTS_DAILYSTATUS_PASSPORTPLACEISSUE"] => string(3) "NCR"
  ["APPLICANTS_DAILYSTATUS_APPIN"] => string(10) "12/21/2013"
  ["APPLICANTS_DAILYSTATUS_MEDICALDATE"] => string(10) "12/21/2013"
  ["APPLICANTS_DAILYSTATUS_MEDICALRESULT"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_NBI"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_NBIRR"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_TRAINING"] => string(3) "Yes"
  ["APPLICANTS_DAILYSTATUS_PDOS"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_TESDA"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_OWWA"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_VISA_DATEISSUE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_VISA_DATEEXPIRE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_STAMPING_FILE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_STAMPING_RELEASE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_CONTRACTIN"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_PROCESSDATE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_BOOKDATE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_DEPLOYEDDATE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_SPEAKENGLISH"] => string(4) "Good"
  ["APPLICANTS_DAILYSTATUS_EDUCATTAINMENT"] => string(16) "High school Grad"
  ["APPLICANTS_DAILYSTATUS_CONTRACTLENGTH"] => string(7) "2 years"
  ["APPLICANTS_DAILYSTATUS_SALARY"] => string(7) "1000USD"
  ["APPLICANTS_DAILYSTATUS_REMARKS"] => string(12) "remarks lang"
  ["APPLICANTS_DAILYSTATUS_ENDCONTRACT_DATE"] => string(0) ""
  ["APPLICANTS_DAILYSTATUS_ISARCHIVE"] => NULL
  ["APPLICANTS_DAILYSTATUS_DATECREATED"] => string(10) "01/04/2014"
  ["APPLICANTS_DAILYSTATUS_DATEUPDATED"] => string(19) "2014-01-10 07:02:20"
}
	 */
	
	//
?>

<div id="bdsummary_wrapper">

	<div id="bdsummary_header">
		<div id="bdsummary_logo">
			<img src="/files/logos/midol_logo.jpg">
		</div>
		<div id="bdsummary_info">
			<p id="companyname">MIDOL INTERNATIONAL HUMAN RESOURCES INC.</p>
			<p id="poea_info">POEA IC. 080-LB-051311-R</p>
			<p id="staddress">No. 8 G/F Mirben Bldg. B Mc Arthur St., Bernardo Compound,</p>
			<p id="cityaddress">Luzon Avenue, Diliman, Quezon  City, Philippines</p>
			<p id="contact_info">Email : midol_international@yahoo.com * website : www.midolmanpower.com</p>
			<p id="telfax">Tel / Fax : 931-3184</p>
		</div>
	</div>
	
	<div id="bdsummary_primarydetails">
		<div id="bdsummary_primarydetails_left">
			<div id="bdsummary_primarydetails_refno">
				<div id="label">Ref No:</div>
				<div id="APPLICANTS_DAILYSTATUS_CODE" class="value"><?php echo $data['APPLICANTS_DAILYSTATUS_CODE'];?></div>
				<div id="arabic_value">رقم المرجع</div>
			</div>
			<div id="bdsummary_primarydetails_name">
				<div id="label">Full Name:</div>
				<div id="APPLICANTS_FULLNAME" class="value"><?php echo $data['APPLICANTS_PERSONAL_DATA_FIRSTNAME']. ' '.$data['APPLICANTS_PERSONAL_DATA_LASTNAME'];?></div>
				<div id="arabic_value">الاسم الكامل</div>
			</div>
			<div id="bdsummary_primarydetails_positionapplied">
				<div id="label">Position Applied:</div>
				<div id="APPLICANTS_PERSONAL_DATA_DESIRED_POSITION" class="value"><?php echo $data['APPLICANTS_PERSONAL_DATA_DESIRED_POSITION'];?></div>
				<div id="arabic_value">موقف تطبيق</div>
			
			</div>
			<div id="bdsummary_primarydetails_dateofbirth">
				<div id="label">Date of Birth:</div>
				<div id="APPLICANTS_PERSONAL_DATA_DATEOFBIRTH" class="value">
					<?php 
					
					$dateofbirth =  $data['APPLICANTS_PERSONAL_DATA_DATEOFBIRTH'];
					$fdb = date('M-d-Y', strtotime($dateofbirth));
					echo $fdb;
					?></div>
				<div id="arabic_value">تاريخ الميلاد</div>
			</div>
			<div id="bdsummary_primarydetails_placeofbirth">
				<div id="label">Place of Birth:</div>
				<div id="APPLICANTS_PERSONAL_DATA_PLACEOFBIRTH" class="value"><?php echo $data['APPLICANTS_PERSONAL_DATA_PLACEOFBIRTH'];?></div>
				<div id="arabic_value">مكان الميلاد</div>
			</div>
			<div id="bdsummary_primarydetails_religion">
				<div id="label">Religion:</div>
				<div id="APPLICANTS_PERSONAL_DATA_RELIGION" class="value"><?php echo $data['APPLICANTS_PERSONAL_DATA_RELIGION'];?></div>
				<div id="arabic_value">دين</div>
			</div>
		</div>
		<div id="bdsummary_primarydetails_wbphoto">
			<div id="bdsummary_primarydetails_wbphoto_img">
				<div id="bdsummary_primarydetails_imgwrapper">
					<img src="/files/wbphotos/<?php echo $data['APPLICANTS_DAILYSTATUS_WBPHOTO'];?>"/>
					
				</div>
			</div>
		</div>
	</div>
	
	<div id="bdsummary_secondarydetails">
		<div id="bdsummary_secondarydetails_firstcol">
			<div id="bdsummary_secondarydetails_firstcol_col">
				<div id="APPLICANTS_DAILYSTATUS_PASSPORT">
					<p id="arabic">جواز سفر رقم
					</p>
					<p id="label">
						Passport No.
					</p>
					<p id="value">
						<?php echo $data['APPLICANTS_DAILYSTATUS_PASSPORT']; ?>
					</p>
				</div>
				<div id="APPLICANTS_DAILYSTATUS_PASSPORTDATEISSUE">
					<p id="arabic">تاريخ الإصدار
					</p>
					<p id="label">
						Date Of Issue
					</p>
					<p id="value">
						<?php 
							$date =  $data['APPLICANTS_DAILYSTATUS_PASSPORTDATEISSUE']; 
							$newdate = date('M-d-Y', strtotime($date));
							echo $newdate
						?>
					</p>
				</div>
				<div id="APPLICANTS_DAILYSTATUS_PASSPORTDATEEXPIRE">
					<p id="arabic">تاريخ انتهاء الصلاحية
					</p>
					<p id="label">
						Expiry Date
					</p>
					<p id="value">
						<?php 
							$date =  $data['APPLICANTS_DAILYSTATUS_PASSPORTDATEEXPIRE']; 
							$newdate = date('M-d-Y', strtotime($date));
							echo $newdate
						?>
					</p>
				</div>
				<div id="APPLICANTS_DAILYSTATUS_PASSPORTPLACEISSUE">
					<p id="arabic">تاريخ الإصدار
					</p>
					<p id="label">
						Place Of Issue
					</p>
					<p id="value">
						<?php echo $data['APPLICANTS_DAILYSTATUS_PASSPORTPLACEISSUE']; ?>
					</p>
				</div>
			</div>
			<div id="bdsummary_secondarydetails_firstcol_col">
				<div id="APPLICANTS_FAMILY_DATA_MARITALSTATUS">
					<p id="arabic">الحالة المدنية
					</p>
					<p id="label">
						Civil Status
					</p>
					<p id="value">
						<?php echo $data['CIVILSTATUS']; ?>
					</p>
				</div>
				<div id="APPLICANTS_FAMILY_DATA_NOOFCHILDREN">
					<p id="arabic">عدد الأطفال
					</p>
					<p id="label">
						No. Of Children
					</p>
					<p id="value">
						<?php 
							echo $data['APPLICANTS_FAMILY_DATA_NOOFCHILDREN']; 
							
						?>
					</p>
				</div>
				<div id="APPLICANTS_DAILYSTATUS_SPEAKENGLISH">
					<p id="arabic">التحدث باللغة الإنجليزية					</p>
					<p id="label">
						Speak English
					</p>
					<p id="value">
						<?php 
							echo  $data['APPLICANTS_DAILYSTATUS_SPEAKENGLISH']; 
							
						?>
					</p>
				</div>
				<div id="APPLICANTS_DAILYSTATUS_EDUCATTAINMENT">
					<p id="arabic">التحصيل العلمي
					</p>
					<p id="label">
						Educ Attainment
					</p>
					<p id="value">
						<?php echo $data['APPLICANTS_DAILYSTATUS_EDUCATTAINMENT']; ?>
					</p>
				</div>
			</div>
		</div>
		<div id="bdsummary_secondarydetails_secondcol">
			<div id="bdsummary_secondarydetails_secondcol_left">
				<div id="bdsummary_secondarydetails_secondcol_left_1">
					<p id="arabic">خبرة في الخارج
					</p>
					<p id="label">
						Experience Abroad
					</p>
					<p id="value">
						<?php 
							if($data['APPLICANTS_PERSONAL_DATA_EXABROAD']) {
								echo 'Ex-Abroad / '.$data['APPLICANTS_PERSONAL_DATA_COUNTRY_ABROAD'];
							} else {
								echo 'First Timer';
							}
						
						?>
					</p>
				</div>
				<div id="bdsummary_secondarydetails_secondcol_left_2">
					<div>
						<p id="arabic">ارتفاع
						</p>
						<p id="label">
							Height
						</p>
						<p id="value">
							<?php 
								echo $data['APPLICANTS_PERSONAL_DATA_HEIGHT'];
							
							?>
						</p>
					</div>
					<div>
						<p id="arabic">الوزن
						</p>
						<p id="label">
							Weight
						</p>
						<p id="value">
							<?php 
								echo $data['APPLICANTS_PERSONAL_DATA_WEIGHT'];
							
							?>
						</p>
					</div>
					<div>
						<p id="arabic">عقد
						</p>
						<p id="label">
							Contract
						</p>
						<p id="value">
							<?php 
								echo $data['APPLICANTS_DAILYSTATUS_CONTRACTLENGTH'];
							
							?>
						</p>
					</div>
					<div>
						<p id="arabic">راتب
						</p>
						<p id="label">
							Salary
						</p>
						<p id="value">
							<?php 
								echo $data['APPLICANTS_DAILYSTATUS_SALARY'];
							
							?>
						</p>
					</div>
				</div>
				<div id="bdsummary_secondarydetails_secondcol_left_3">
					<div id="allaroundwork">
						<p id="arabic">في جميع أنحاء الأعمال المنزلية					
							</p>
						<p id="label">
							All Around Housework
						</p>
						<p id="value">
							LAUNDRY, IRONING, DISHWASHING & CARWASHING
						</p>
					</div>
				</div>
			</div>
			<div id="bdsummary_secondarydetails_secondcol_right">
				<div>
					<p>تصريحات</p>
					<p>Remarks :</p> 
					<ul>
						
					<?php 
						if($data['APPLICANTS_PERSONAL_DATA_EXABROAD']) {
							echo '<li>EXPERIENCE ABROAD</li>';
						} else {
							echo '<li>FIRST TIMER</li>';
						}
						
						echo  '<li>'.$data['CIVILSTATUS'].''.$data['APPLICANTS_PERSONAL_DATA_AGE'].' YRS OLD'.($data['APPLICANTS_FAMILY_DATA_NOOFCHILDREN'] ? ' / '.$data['APPLICANTS_FAMILY_DATA_NOOFCHILDREN'].' Kids': '').'</li>' ;
						
						if($data['APPLICANTS_DAILYSTATUS_EDUCATTAINMENT']) {
							echo '<li>'.$data['APPLICANTS_DAILYSTATUS_EDUCATTAINMENT'].'</li>';
						}
						
						echo '<li>WILLING TO FINISH CONTRACT W/O DAY OFF AND MOBILE PHONE</li>';
						echo '<li>WILLING TO LEARN TO SPEAK ARABIC</li>';
						echo '<li>WILLING TO LEARN TO COOK ARABIC FOOD</li>';
						echo '<li>KNOWLEDGEABLE IN ALL HOUSEHOLD CHORES</li>';
						echo '<li>CAN SPEAK AND WRITE ENGLISH</li>';
						echo '<li>HARDWORKING, TRUSTWORTHY, AND OBEDIENT</li>';
					?>
					</ul>
				</div>
			</div>
		</div>
		<div id="bdsummary_secondarydetails_thirdcol">
			<div>
				<p id="arabic">
					علامة على أصحاب العمل
				</p>
				<p id="label">
					Sign of Employer
				</p>
			</div>
			
			<div>
				<p id="arabic">
					علامة على مقدم الطلب
				</p>
				<p id="label">
					Sign of Applicant
				</p>
			</div>
			
			<div>
				<p id="arabic">
					مقابلة بواسطة
				</p>
				<p id="label">
					Interviewed By:
				</p>
			</div>
		</div>
	</div>
</div>