<?php 
	$params = $this->params;
	
	if($params['ident'] == 'APPLICANTS_DAILYSTATUS_CONTACTNUMBER') {
		$colname = 'Contact No.';	
		$nameid = 'inputContactno';
		$type = 'input';
	} 
	
	if($params['ident'] == 'APPLICANTS_DAILYSTATUS_NBI') {
		$colname = 'NBI';	
		$nameid = 'datenbi';
		$type = 'cal';
	} 
	
	if($params['ident'] == 'APPLICdANTS_DAILYSTATUS_NBIRR') {
		$colname = 'NBI';
		$nameid = 'datenbirr';
		$type = 'cal';
	}
	
	//
?>

	
<form class="form-horizontal" id="newAppDailystatus" name="newAppDailystatus" action="/Dailystatus" method="post" />
	<fieldset>
	<input type="hidden" name="inputAppDataId" id="inputAppDataId" value="<?php echo $params['appid'];?>">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">X</button>
		<h3>Set <span class="applicantsName"><?php echo $params['name']; ?></span>'s  <span class="columnName"> <?php echo $colname; ?></span></h3> 
	</div>
	<div class="modal-body">
		<p id="id"></p>
	
	<?php 
	
		if($type == 'input') {
			echo '<div class="control-group ">
			<label for="'.$nameid.'" class="control-label">'.$colname.'</label>
			<div class="controls">
			  <input type="text" id="'.$nameid.'" name="'.$nameid.'" />
			</div>
		  </div> ';
		} elseif ($type = 'cal') {
			echo '<div class="control-group">
				  <label class="control-label" for="'.$nameid.'">'.$colname.'</label>
				  <div class="controls">
					<input type="text" class="input-xlarge datepicker" id="'.$nameid.'" name="'.$nameid.'" value="" />
				  </div>
				</div>';
		}
	?>
		
		
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
		<a href="#" id="newAppDailystatusModal" class="btn btn-primary">Save changes</a>
	</div>
	</fieldset>
</form>