
		<div class="container-fluid-full">
		<div class="row-fluid">
					
			<div class="row-fluid">
				<div class="login-box">
					<h2>Login to your account</h2>
					<form class="form-horizontal" action="login" method="post" />
						<fieldset>
							
							<input class="input-large span12" name="username" id="username" type="text" placeholder="type username" />

							<input class="input-large span12" name="password" id="password" type="password" placeholder="type password" />

							<div class="clearfix"></div>
							<?php if ($this->loginfailed) { ?>
							<div class="alert alert-error">
								<strong> <?php echo $this->errorlogin; ?></strong>
							</div>
							
							<?php } ?>
							<button type="submit" class="btn btn-primary span12">Login</button>
						</fieldset>	

					</form>
	
				</div>
			</div><!--/row-->
			
				</div><!--/fluid-row-->
				
	</div><!--/.fluid-container-->
