<?php

class Application_Model_ApplicantsDailyStatus
{
	//declare the user's attributes
	//private $APPLICANTS_DAILYSTATUS_ID;
	private $APPLICANTS_PERSONAL_DATA_ID;
	private $AGENTBRANCH_ID;
	private $APPLICANTS_DAILYSTATUS_CONTACTNUMBER;
	private $APPLICANTS_DAILYSTATUS_WBPHOTO;
	private $APPLICANTS_DAILYSTATUS_PASSPORT;
	private $APPLICANTS_DAILYSTATUS_PASSPORTDATEISSUE;
	private $APPLICANTS_DAILYSTATUS_PASSPORTDATEEXPIRE;
	private $APPLICANTS_DAILYSTATUS_PASSPORTPLACEISSUE;
	private $APPLICANTS_DAILYSTATUS_APPIN;
	private $APPLICANTS_DAILYSTATUS_MEDICALDATE;
	private $APPLICANTS_DAILYSTATUS_MEDICALRESULT;
	private $APPLICANTS_DAILYSTATUS_NBI;
	private $APPLICANTS_DAILYSTATUS_NBIRR;
	private $APPLICANTS_DAILYSTATUS_TRAINING;
	private $APPLICANTS_DAILYSTATUS_PDOS;
	private $APPLICANTS_DAILYSTATUS_TESDA;
	private $APPLICANTS_DAILYSTATUS_OWWA;
	private $APPLICANTS_DAILYSTATUS_POEA;
	private $APPLICANTS_DAILYSTATUS_VISA_DATEISSUE;
	private $APPLICANTS_DAILYSTATUS_VISA_DATEEXPIRE;
	private $APPLICANTS_DAILYSTATUS_STAMPING_FILE;
	private $APPLICANTS_DAILYSTATUS_STAMPING_RELEASE;
	private $APPLICANTS_DAILYSTATUS_CONTRACTIN;
	private $APPLICANTS_DAILYSTATUS_PROCESSDATE;
	private $APPLICANTS_DAILYSTATUS_SERUM;
	private $APPLICANTS_DAILYSTATUS_BOOKDATE;
	private $APPLICANTS_DAILYSTATUS_DEPLOYEDDATE;
	private $APPLICANTS_DAILYSTATUS_SPEAKENGLISH;
	private $APPLICANTS_DAILYSTATUS_EDUCATTAINMENT;
	private $APPLICANTS_DAILYSTATUS_SALARY;
	private $APPLICANTS_DAILYSTATUS_CONTRACTLENGTH;
	private $APPLICANTS_DAILYSTATUS_REMARKS;
	private $APPLICANTS_DAILYSTATUS_ENDCONTRACT_DATE;
	private $APPLICANTS_DAILYSTATUS_ISARCHIVE;
	private $APPLICANTS_DAILYSTATUS_DATECREATED;
	private $APPLICANTS_DAILYSTATUS_DATEUPDATED;
	private $APPLICANTS_DAILYSTATUS_CODE;
	
	
	//upon construction, map the values
	//from the $sysmodules_row if available
	public function __construct($sysmodules_row = null)
	{
		if( !is_null($sysmodules_row) && $sysmodules_row instanceof Zend_Db_Table_Row ) {
			//$this->APPLICANTS_DAILYSTATUS_ID = $sysmodules_row->APPLICANTS_DAILYSTATUS_ID;
			$this->APPLICANTS_PERSONAL_DATA_ID = $sysmodules_row->APPLICANTS_PERSONAL_DATA_ID;
			$this->APPLICANTS_DAILYSTATUS_CODE = $sysmodules_row->APPLICANTS_DAILYSTATUS_CODE;
			$this->AGENTBRANCH_ID = $sysmodules_row->AGENTBRANCH_ID; //APPLICANTS_DAILYSTATUS_WBPHOTO
			$this->APPLICANTS_DAILYSTATUS_WBPHOTO = $sysmodules_row->APPLICANTS_DAILYSTATUS_WBPHOTO;
			$this->APPLICANTS_DAILYSTATUS_CONTACTNUMBER = $sysmodules_row->APPLICANTS_DAILYSTATUS_CONTACTNUMBER;
			$this->APPLICANTS_DAILYSTATUS_PASSPORT = $sysmodules_row->APPLICANTS_DAILYSTATUS_PASSPORT;
			$this->APPLICANTS_DAILYSTATUS_PASSPORTDATEISSUE = $sysmodules_row->APPLICANTS_DAILYSTATUS_PASSPORTDATEISSUE;
			$this->APPLICANTS_DAILYSTATUS_PASSPORTDATEEXPIRE = $sysmodules_row->APPLICANTS_DAILYSTATUS_PASSPORTDATEEXPIRE;
			$this->APPLICANTS_DAILYSTATUS_PASSPORTPLACEISSUE = $sysmodules_row->APPLICANTS_DAILYSTATUS_PASSPORTPLACEISSUE;
			$this->APPLICANTS_DAILYSTATUS_APPIN = $sysmodules_row->APPLICANTS_DAILYSTATUS_APPIN;
			$this->APPLICANTS_DAILYSTATUS_MEDICALDATE = $sysmodules_row->APPLICANTS_DAILYSTATUS_MEDICALDATE;
			$this->APPLICANTS_DAILYSTATUS_MEDICALRESULT = $sysmodules_row->APPLICANTS_DAILYSTATUS_MEDICALRESULT;
			$this->APPLICANTS_DAILYSTATUS_NBI = $sysmodules_row->APPLICANTS_DAILYSTATUS_NBI;
			$this->APPLICANTS_DAILYSTATUS_NBIRR = $sysmodules_row->APPLICANTS_DAILYSTATUS_NBIRR;
			$this->APPLICANTS_DAILYSTATUS_TRAINING = $sysmodules_row->APPLICANTS_DAILYSTATUS_TRAINING;
			$this->APPLICANTS_DAILYSTATUS_PDOS = $sysmodules_row->APPLICANTS_DAILYSTATUS_PDOS;
			$this->APPLICANTS_DAILYSTATUS_TESDA = $sysmodules_row->APPLICANTS_DAILYSTATUS_TESDA;
			$this->APPLICANTS_DAILYSTATUS_OWWA = $sysmodules_row->APPLICANTS_DAILYSTATUS_OWWA;
			$this->APPLICANTS_DAILYSTATUS_POEA = $sysmodules_row->APPLICANTS_DAILYSTATUS_POEA;
			$this->APPLICANTS_DAILYSTATUS_VISA_DATEISSUE = $sysmodules_row->APPLICANTS_DAILYSTATUS_VISA_DATEISSUE;
			$this->APPLICANTS_DAILYSTATUS_VISA_DATEEXPIRE = $sysmodules_row->APPLICANTS_DAILYSTATUS_VISA_DATEEXPIRE;
			$this->APPLICANTS_DAILYSTATUS_STAMPING_FILE = $sysmodules_row->APPLICANTS_DAILYSTATUS_STAMPING_FILE;
			$this->APPLICANTS_DAILYSTATUS_STAMPING_RELEASE = $sysmodules_row->APPLICANTS_DAILYSTATUS_STAMPING_RELEASE;
			$this->APPLICANTS_DAILYSTATUS_CONTRACTIN = $sysmodules_row->APPLICANTS_DAILYSTATUS_CONTRACTIN;
			$this->APPLICANTS_DAILYSTATUS_PROCESSDATE = $sysmodules_row->APPLICANTS_DAILYSTATUS_PROCESSDATE;
			$this->APPLICANTS_DAILYSTATUS_SERUM = $sysmodules_row->APPLICANTS_DAILYSTATUS_SERUM;
			$this->APPLICANTS_DAILYSTATUS_BOOKDATE = $sysmodules_row->APPLICANTS_DAILYSTATUS_BOOKDATE;
			$this->APPLICANTS_DAILYSTATUS_DEPLOYEDDATE = $sysmodules_row->APPLICANTS_DAILYSTATUS_DEPLOYEDDATE; //APPLICANTS_DAILYSTATUS_EDUCATTAINMENT
			$this->APPLICANTS_DAILYSTATUS_SPEAKENGLISH = $sysmodules_row->APPLICANTS_DAILYSTATUS_SPEAKENGLISH;
			$this->APPLICANTS_DAILYSTATUS_EDUCATTAINMENT = $sysmodules_row->APPLICANTS_DAILYSTATUS_EDUCATTAINMENT;
			$this->APPLICANTS_DAILYSTATUS_CONTRACTLENGTH = $sysmodules_row->APPLICANTS_DAILYSTATUS_CONTRACTLENGTH;
			$this->APPLICANTS_DAILYSTATUS_SALARY = $sysmodules_row->APPLICANTS_DAILYSTATUS_SALARY;
			$this->APPLICANTS_DAILYSTATUS_REMARKS = $sysmodules_row->APPLICANTS_DAILYSTATUS_REMARKS;
			$this->APPLICANTS_DAILYSTATUS_ENDCONTRACT_DATE = $sysmodules_row->APPLICANTS_DAILYSTATUS_ENDCONTRACT_DATE;
			$this->APPLICANTS_DAILYSTATUS_ISARCHIVE = $sysmodules_row->APPLICANTS_DAILYSTATUS_ISARCHIVE;
			$this->APPLICANTS_DAILYSTATUS_DATECREATED = $sysmodules_row->APPLICANTS_DAILYSTATUS_DATECREATED;
			$this->APPLICANTS_DAILYSTATUS_DATEUPDATED = $sysmodules_row->APPLICANTS_DAILYSTATUS_DATEUPDATED;
			
		}
	}
	
	//magic function __set to set the
	//attributes of the User model
	public function __set($name, $value)
	{
		switch($name) {
			case 'APPLICANTS_PERSONAL_DATA_ID':
				//if the id isn't null, you shouldn't update it!
				if( !is_null($this->APPLICANTS_PERSONAL_DATA_ID) ) {
					throw new Exception('Cannot update APPLICANTS_PERSONAL_DATA_ID!');
				}
				break;
		}
			
		//set the attribute with the value
		$this->$name = $value;
	}
	
	public function __get($name)
	{
		return $this->$name;
	}
	
	public function __getProperties()
	{
		return get_object_vars($this);
	}

}

