<div class="row-fluid">	
				<div class="span12">

					<div class="box-content">
						
						<a class="quick-button span2" href="/Applicantdata/newpersonaldata">
							<i class="icon-tasks"></i>
							<p>New Bio-Data</p>
							<span class="notification blue">
							<?php 
							
								$objbiodata = new Application_Model_ApplicantsPersonalDataMapper();
								$totalrows = $objbiodata->getTotalrows();
								echo $totalrows;
							?>
							</span>
						</a>
						<a class="quick-button span2" href="/Dailystatus/new">
							<i class="icon-calendar"></i>
							<p>New Daily Status</p>
							<span class="notification red">
							<?php 
							
								$objbiodata = new Application_Model_ApplicantsDailyStatusMapper();
								$totalrows = $objbiodata->getTotalrows();
								echo $totalrows;
							?>
							</span>
						</a>
						<a class="quick-button span2" href="/Applicantdata/search">
							<i class="icon-group"></i>
							<p>Search</p>
							<span class="notification green"></span>
						</a>
						<a class="quick-button span2" href="/Dailystatus/appdeployed">
							<i class="icon-link"></i>
							<p>Deployed</p>
							<span class="notification green">
							<?php 
							$objbiodata = new Application_Model_ApplicantsDailyStatusMapper();
							$totalrows = $objbiodata->getdeployedTotalrows();
							echo $totalrows;
							?>
							</span>
						</a>
						<a class="quick-button span2">
							<i class="icon-suitcase"></i>
							<p>Book</p>
							<span class="notification green"></span>
						</a>
						<a class="quick-button span2">
							<i class="icon-sign-blank"></i>
							<p>Passport Details</p>
						</a>
						
						<div class="clearfix"></div>
					</div>	
				</div><!--/span-->
				
			</div><!--/row-->
			
			<div class="clearfix">&nbsp;</div>